---
apiVersion: v1
kind: Service
metadata:
  labels:
    name: mongodb
  name: mongodb
  namespace: pacman
spec:
  ports:
  - port: 27017
    protocol: TCP
    targetPort: 27017
  selector:
    app: mongodb
  sessionAffinity: None
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  labels:
    name: pacman
  name: pacman
  namespace: pacman
spec:
  type: NodePort
  ports:
  - port: 80
    protocol: TCP
    targetPort: 8080
    nodePort: 32001
  selector:
    app: pacman
  sessionAffinity: None
